[package]
name = "pingquery"
version = "0.1.0"
authors = ["Ryan P. Brewster <RyanPBrewster@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8"
futures-core = "0.3"
log = "0.4"
prost = "0.7"
rusqlite = "0.25"
structopt = "0.3"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync", "time"] }
tonic = "0.4"

[build-dependencies]
tonic-build = "0.4"
